import java.awt.Color;
import java.awt.Font;
import java.awt.Insets;
import javax.swing.JPanel;


public class ButtonPanel extends JPanel
{
	static MyButton AC,plmin,per,div,seven,eight,nine,inc,four,five,six,minus,one,two,three,plus,zero,point,result;
	Color grey = new Color(54, 54, 54);
	Color lightGrey = new Color(181, 181, 181);
	Color orange = new Color(238, 154, 0);
	Font font = new Font("Colibri",Font.BOLD,20);
	
	public ButtonPanel(CLogic cl)
	{
		setLayout(null);
		setBounds(10,50,230,290);
		setBackground(new Color(28, 28, 28));
		
		AC = new MyButton("AC");
		AC.setBounds(0, 0, 50, 50);
		AC.setBackground(lightGrey);
		AC.addActionListener(cl.ao);
		AC.setBorder(null);
		AC.setActionCommand("AC");
		AC.setMargin(new Insets(0, 0, 0, 0));
		AC.setFont(font);
		add(AC);
		plmin = new MyButton("+/-");
		plmin.setBounds(60, 0, 50, 50);
		plmin.setBackground(lightGrey);
		plmin.addActionListener(cl.ao);
		plmin.setBorder(null);
		plmin.setActionCommand("+/-");
		plmin.setMargin(new Insets(0, 0, 0, 0));
		plmin.setFont(font);
		add(plmin);
		per = new MyButton("%");
		per.setBounds(120, 0, 50, 50);
		per.setBackground(lightGrey);
		per.addActionListener(cl.ao);
		per.setBorder(null);
		per.setActionCommand("%");
		per.setMargin(new Insets(0, 0, 0, 0));
		per.setFont(font);
		add(per);
		div = new MyButton("÷");
		div.setBounds(180, 0, 50, 50);
		div.setBackground(orange);
		div.addActionListener(cl.ao);
		div.setBorder(null);
		div.setActionCommand("/");
		div.setMargin(new Insets(0, 0, 0, 0));
		div.setFont(font);
		div.setForeground(Color.WHITE);
		add(div);
		seven = new MyButton("7");
		seven.setBounds(0, 60, 50, 50);
		seven.setBackground(grey);
		seven.addActionListener(cl.ao);
		seven.setBorder(null);
		seven.setActionCommand("7");
		seven.setMargin(new Insets(0, 0, 0, 0));
		seven.setFont(font);
		seven.setForeground(Color.WHITE);
		add(seven);
		eight = new MyButton("8");
		eight.setBounds(60, 60, 50, 50);
		eight.setBackground(grey);
		eight.addActionListener(cl.ao);
		eight.setBorder(null);
		eight.setActionCommand("8");
		eight.setMargin(new Insets(0, 0, 0, 0));
		eight.setFont(font);
		eight.setForeground(Color.WHITE);
		add(eight);
		nine = new MyButton("9");
		nine.setBounds(120, 60, 50, 50);
		nine.setBackground(grey);
		nine.addActionListener(cl.ao);
		nine.setBorder(null);
		nine.setActionCommand("9");
		nine.setMargin(new Insets(0, 0, 0, 0));
		nine.setFont(font);
		nine.setForeground(Color.WHITE);
		add(nine);
		inc = new MyButton("x");
		inc.setBounds(180, 60, 50, 50);
		inc.setBackground(orange);
		inc.addActionListener(cl.ao);
		inc.setBorder(null);
		inc.setActionCommand("*");
		inc.setMargin(new Insets(0, 0, 0, 0));
		inc.setFont(font);
		inc.setForeground(Color.WHITE);
		add(inc);
		four = new MyButton("4");
		four.setBounds(0, 120, 50, 50);
		four.setBackground(grey);
		four.addActionListener(cl.ao);
		four.setBorder(null);
		four.setActionCommand("4");
		four.setMargin(new Insets(0, 0, 0, 0));
		four.setFont(font);
		four.setForeground(Color.WHITE);
		add(four);
		five = new MyButton("5");
		five.setBounds(60, 120, 50, 50);
		five.setBackground(grey);
		five.addActionListener(cl.ao);
		five.setBorder(null);
		five.setActionCommand("5");
		five.setMargin(new Insets(0, 0, 0, 0));
		five.setFont(font);
		five.setForeground(Color.WHITE);
		add(five);
		six = new MyButton("6");
		six.setBounds(120, 120, 50, 50);
		six.setBackground(grey);
		six.addActionListener(cl.ao);
		six.setBorder(null);
		six.setActionCommand("6");
		six.setMargin(new Insets(0, 0, 0, 0));
		six.setFont(font);
		six.setForeground(Color.WHITE);
		add(six);
		minus = new MyButton("-");
		minus.setBounds(180, 120, 50, 50);
		minus.setBackground(orange);
		minus.addActionListener(cl.ao);
		minus.setBorder(null);
		minus.setActionCommand("-");
		minus.setMargin(new Insets(0, 0, 0, 0));
		minus.setFont(font);
		minus.setForeground(Color.WHITE);
		add(minus);
		one = new MyButton("1");
		one.setBounds(0, 180, 50, 50);
		one.setBackground(grey);
		one.addActionListener(cl.ao);
		one.setBorder(null);
		one.setActionCommand("1");
		one.setMargin(new Insets(0, 0, 0, 0));
		one.setFont(font);
		one.setForeground(Color.WHITE);
		add(one);
		two = new MyButton("2");
		two.setBounds(60, 180, 50, 50);
		two.setBackground(grey);
		two.addActionListener(cl.ao);
		two.setBorder(null);
		two.setActionCommand("2");
		two.setMargin(new Insets(0, 0, 0, 0));
		two.setFont(font);
		two.setForeground(Color.WHITE);
		add(two);
		three = new MyButton("3");
		three.setBounds(120, 180, 50, 50);
		three.setBackground(grey);
		three.addActionListener(cl.ao);
		three.setBorder(null);
		three.setActionCommand("3");
		three.setMargin(new Insets(0, 0, 0, 0));
		three.setFont(font);
		three.setForeground(Color.WHITE);
		add(three);
		plus = new MyButton("+");
		plus.setBounds(180, 180, 50, 50);
		plus.setBackground(orange);
		plus.addActionListener(cl.ao);
		plus.setBorder(null);
		plus.setActionCommand("+");
		plus.setMargin(new Insets(0, 0, 0, 0));
		plus.setFont(font);
		plus.setForeground(Color.WHITE);
		add(plus);
		zero = new MyButton("0");
		zero.setBounds(0, 240, 110, 50);
		zero.setBackground(grey);
		zero.addActionListener(cl.ao);
		zero.setBorder(null);
		zero.setActionCommand("0");
		zero.setMargin(new Insets(0, 0, 0, 0));
		zero.setFont(font);
		zero.setForeground(Color.WHITE);
		add(zero);
		point = new MyButton(".");
		point.setBounds(120, 240, 50, 50);
		point.setBackground(grey);
		point.addActionListener(cl.ao);
		point.setBorder(null);
		point.setActionCommand(".");
		point.setMargin(new Insets(0, 0, 0, 0));
		point.setFont(font);
		point.setForeground(Color.WHITE);
		add(point);
		result = new MyButton("=");
		result.setBounds(180, 240, 50, 50);
		result.setBackground(orange);
		result.addActionListener(cl.ao);
		result.setBorder(null);
		result.setActionCommand("=");
		result.setMargin(new Insets(0, 0, 0, 0));
		result.setFont(font);
		result.setForeground(Color.WHITE);
		add(result);
	}
}
